name: dynamicdns
description: Dynamic DNS
annotations:
  title: Dynamic DNS
type: application
version: 1.0.0
apiVersion: v2
appVersion: 1.0.0
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: Jorge
    url: https://jorgesanchezcarlin.es/
    email: info@jorgesanchezcarlin.es
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://jorgesanchezcarlin.es/
icon: https://raw.githubusercontent.com/jorequis/truenascharts/main/dynamicdns.png
sources:
  - https://jorgesanchezcarlin.es
keywords:
  - dynamicdns
